"""Seed real-world data brokers into the database.

Run: python manage.py seed_brokers
"""

from django.core.management.base import BaseCommand

BROKERS = [
    # People Search Sites
    {
        "name": "BeenVerified",
        "slug": "beenverified",
        "website_url": "https://www.beenverified.com",
        "category": "people_search",
        "description": "People search site that aggregates public records and contact info.",
        "opt_out_url": "https://www.beenverified.com/optout",
        "opt_out_email": "privacy@beenverified.com",
        "removal_method": "web_form",
        "web_form_config": {
            "url": "https://www.beenverified.com/optout/search",
            "steps": [
                {"action": "goto", "value": "https://www.beenverified.com/optout/search"},
                {"action": "fill", "selector": "input[name='firstname']", "value": "{full_name}"},
                {"action": "click", "selector": "button[type='submit']"},
            ],
        },
        "requires_identity": True,
        "estimated_days": 7,
        "priority": 100,
    },
    {
        "name": "Spokeo",
        "slug": "spokeo",
        "website_url": "https://www.spokeo.com",
        "category": "people_search",
        "description": "People search engine with public records and reverse lookups.",
        "opt_out_url": "https://www.spokeo.com/optout",
        "opt_out_email": "privacy@spokeo.com",
        "removal_method": "web_form",
        "requires_identity": True,
        "estimated_days": 7,
        "priority": 99,
    },
    {
        "name": "WhitePages",
        "slug": "whitepages",
        "website_url": "https://www.whitepages.com",
        "category": "people_search",
        "description": "White pages directory with phone numbers and addresses.",
        "opt_out_url": "https://www.whitepages.com/suppression_requests",
        "opt_out_email": "dataprivacy@whitepages.com",
        "removal_method": "both",
        "requires_identity": True,
        "estimated_days": 10,
        "priority": 98,
    },
    {
        "name": "Intelius",
        "slug": "intelius",
        "website_url": "https://www.intelius.com",
        "category": "people_search",
        "description": "People search and background check site.",
        "opt_out_email": "privacy@intelius.com",
        "removal_method": "email",
        "requires_identity": True,
        "estimated_days": 7,
        "priority": 97,
    },
    {
        "name": "PeopleFinder",
        "slug": "peoplefinder",
        "website_url": "https://www.peoplefinder.com",
        "category": "people_search",
        "description": "People search site that aggregates public records.",
        "opt_out_email": "support@peoplefinder.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 96,
    },
    {
        "name": "TruePeopleSearch",
        "slug": "truepeoplesearch",
        "website_url": "https://www.truepeoplesearch.com",
        "category": "people_search",
        "description": "Free people search engine.",
        "opt_out_url": "https://www.truepeoplesearch.com/removal",
        "opt_out_email": "admin@truepeoplesearch.com",
        "removal_method": "both",
        "estimated_days": 14,
        "priority": 95,
    },
    {
        "name": "ZabaSearch",
        "slug": "zabasearch",
        "website_url": "https://www.zabasearch.com",
        "category": "people_search",
        "description": "People search with phone and address lookup.",
        "opt_out_url": "https://www.zabasearch.com/optout",
        "opt_out_email": "legal@zabasearch.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 94,
    },
    {
        "name": "Radaris",
        "slug": "radaris",
        "website_url": "https://www.radaris.com",
        "category": "people_search",
        "description": "People search, background check, and public records.",
        "opt_out_url": "https://radaris.com/page/opt-out",
        "opt_out_email": "support@radaris.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 93,
    },
    {
        "name": "Mylife",
        "slug": "mylife",
        "website_url": "https://www.mylife.com",
        "category": "people_search",
        "description": "People search and public profile site.",
        "opt_out_url": "https://www.mylife.com/privacy",
        "opt_out_email": "privacy@mylife.com",
        "removal_method": "email",
        "requires_identity": True,
        "estimated_days": 14,
        "priority": 92,
    },
    {
        "name": "USSearch",
        "slug": "ussearch",
        "website_url": "https://www.ussearch.com",
        "category": "people_search",
        "description": "People search and background check service.",
        "opt_out_email": "privacy@ussearch.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 91,
    },
    {
        "name": "PeekYou",
        "slug": "peekyou",
        "website_url": "https://www.peekyou.com",
        "category": "people_search",
        "description": "People search engine that indexes social media profiles.",
        "opt_out_url": "https://www.peekyou.com/about/contact/optout",
        "opt_out_email": "privacy@peekyou.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 90,
    },
    {
        "name": "FastPeopleSearch",
        "slug": "fastpeoplesearch",
        "website_url": "https://www.fastpeoplesearch.com",
        "category": "people_search",
        "description": "Free people search engine.",
        "opt_out_url": "https://www.fastpeoplesearch.com/removal",
        "opt_out_email": "privacy@fastpeoplesearch.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 89,
    },
    {
        "name": "Nextdoor",
        "slug": "nextdoor",
        "website_url": "https://nextdoor.com",
        "category": "social_media",
        "description": "Neighborhood social network that indexes member profiles.",
        "opt_out_url": "https://help.nextdoor.com/s/article/Delete-your-account",
        "opt_out_email": "privacy@nextdoor.com",
        "removal_method": "email",
        "estimated_days": 7,
        "priority": 88,
    },

    # Data Brokers (the big ones that sell data)
    {
        "name": "Acxiom",
        "slug": "acxiom",
        "website_url": "https://www.acxiom.com",
        "category": "data_broker",
        "description": "One of the largest data brokers. Collects and sells personal data to marketers.",
        "opt_out_url": "https://isapps.acxiom.com/optout/optout.aspx",
        "opt_out_email": "consumer@acxiom.com",
        "removal_method": "both",
        "estimated_days": 30,
        "priority": 80,
    },
    {
        "name": "Experian",
        "slug": "experian",
        "website_url": "https://www.experian.com",
        "category": "data_broker",
        "description": "Credit bureau and data broker that sells consumer marketing data.",
        "opt_out_url": "https://www.experian.com/privacy/opt-out",
        "opt_out_email": "privacy@experian.com",
        "removal_method": "both",
        "estimated_days": 30,
        "priority": 80,
    },
    {
        "name": "Equifax",
        "slug": "equifax",
        "website_url": "https://www.equifax.com",
        "category": "data_broker",
        "description": "Credit bureau that also operates as a data broker.",
        "opt_out_url": "https://www.equifax.com/personal/credit-report-services/credit-report-opt-out",
        "opt_out_email": "privacy@equifax.com",
        "removal_method": "both",
        "estimated_days": 30,
        "priority": 80,
    },
    {
        "name": "Epsilon",
        "slug": "epsilon",
        "website_url": "https://www.epsilon.com",
        "category": "data_broker",
        "description": "Marketing data and email deployment company.",
        "opt_out_email": "privacy@epsilon.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 80,
    },
    {
        "name": "Oracle Data Cloud",
        "slug": "oracle-data-cloud",
        "website_url": "https://www.oracle.com/marketingcloud/data-cloud",
        "category": "data_broker",
        "description": "Oracle's data brokerage arm. Sells highly detailed consumer profiles.",
        "opt_out_url": "https://datacloudoptout.oracle.com",
        "opt_out_email": "privacy@oracle.com",
        "removal_method": "both",
        "estimated_days": 30,
        "priority": 80,
    },
    {
        "name": "LexisNexis",
        "slug": "lexisnexis",
        "website_url": "https://www.lexisnexis.com",
        "category": "data_broker",
        "description": "Legal, risk, and data analytics company. Sells consumer data.",
        "opt_out_url": "https://www.lexisnexis.com/privacy/for-individuals/data-subject-rights",
        "opt_out_email": "privacy@lexisnexis.com",
        "removal_method": "both",
        "estimated_days": 30,
        "priority": 80,
    },
    {
        "name": "Corelogic",
        "slug": "corelogic",
        "website_url": "https://www.corelogic.com",
        "category": "data_broker",
        "description": "Property and mortgage data provider that also sells consumer data.",
        "opt_out_email": "privacy@corelogic.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 80,
    },
    {
        "name": "CDK Global",
        "slug": "cdk-global",
        "website_url": "https://www.cdkglobal.com",
        "category": "data_broker",
        "description": "Automotive data broker.",
        "opt_out_email": "privacy@cdkglobal.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 80,
    },
    {
        "name": "FICO",
        "slug": "fico",
        "website_url": "https://www.fico.com",
        "category": "data_broker",
        "description": "Credit scoring company that also sells consumer data.",
        "opt_out_email": "privacy@fico.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 80,
    },
    {
        "name": "TransUnion",
        "slug": "transunion",
        "website_url": "https://www.transunion.com",
        "category": "data_broker",
        "description": "Credit bureau and data broker.",
        "opt_out_url": "https://www.transunion.com/privacy/optout",
        "opt_out_email": "privacy@transunion.com",
        "removal_method": "both",
        "estimated_days": 30,
        "priority": 80,
    },
    {
        "name": "Zillow",
        "slug": "zillow",
        "website_url": "https://www.zillow.com",
        "category": "data_broker",
        "description": "Real estate data aggregator with homeowner information.",
        "opt_out_url": "https://www.zillow.com/zestimate/optout",
        "opt_out_email": "privacy@zillow.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 79,
    },
    {
        "name": "High Speed Internet",
        "slug": "high-speed-internet",
        "website_url": "https://www.highspeedinternet.com",
        "category": "data_broker",
        "description": "Telecom data aggregator that sells consumer data.",
        "opt_out_email": "privacy@highspeedinternet.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 79,
    },
    {
        "name": "Verizon Media",
        "slug": "verizon-media",
        "website_url": "https://www.verizonmedia.com",
        "category": "data_broker",
        "description": "Digital advertising and audience data.",
        "opt_out_url": "https://www.aboutads.info",
        "opt_out_email": "privacy@verizonmedia.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 79,
    },
    {
        "name": "Retail Data Companies",
        "slug": "retail-data",
        "website_url": "https://www.example.com",
        "category": "data_broker",
        "description": "Retail loyalty and purchase data providers.",
        "opt_out_email": "privacy@retaildata.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 79,
    },
    {
        "name": "Ad Companies",
        "slug": "ad-companies",
        "website_url": "https://www.example.com",
        "category": "data_broker",
        "description": "Advertising networks and ad targeting data.",
        "opt_out_email": "privacy@adcompanies.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 79,
    },
    {
        "name": "P.O.S. Companies",
        "slug": "pos-companies",
        "website_url": "https://www.example.com",
        "category": "data_broker",
        "description": "Point-of-sale transaction data providers.",
        "opt_out_email": "privacy@poscompanies.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 79,
    },
    {
        "name": "Financial Data Companies",
        "slug": "financial-data",
        "website_url": "https://www.example.com",
        "category": "data_broker",
        "description": "Financial and transaction data aggregators.",
        "opt_out_email": "privacy@financialdata.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 79,
    },

    # Background Check Sites
    {
        "name": "CheckPeople",
        "slug": "checkpeople",
        "website_url": "https://www.checkpeople.com",
        "category": "background_check",
        "description": "Background check and people search.",
        "opt_out_url": "https://www.checkpeople.com/optout",
        "opt_out_email": "support@checkpeople.com",
        "removal_method": "both",
        "requires_identity": True,
        "estimated_days": 14,
        "priority": 70,
    },
    {
        "name": "Instant Checkmate",
        "slug": "instant-checkmate",
        "website_url": "https://www.instantcheckmate.com",
        "category": "background_check",
        "description": "Background check site with criminal records.",
        "opt_out_url": "https://www.instantcheckmate.com/optout",
        "opt_out_email": "privacy@instantcheckmate.com",
        "removal_method": "both",
        "requires_identity": True,
        "estimated_days": 14,
        "priority": 70,
    },
    {
        "name": "PeopleLooker",
        "slug": "peoplelooker",
        "website_url": "https://www.peoplelooker.com",
        "category": "background_check",
        "description": "Background check site.",
        "opt_out_url": "https://www.peoplelooker.com/optout",
        "opt_out_email": "privacy@peoplelooker.com",
        "removal_method": "both",
        "estimated_days": 14,
        "priority": 70,
    },
    {
        "name": "TruthFinder",
        "slug": "truthfinder",
        "website_url": "https://www.truthfinder.com",
        "category": "background_check",
        "description": "Background check site.",
        "opt_out_url": "https://www.truthfinder.com/optout",
        "opt_out_email": "privacy@truthfinder.com",
        "removal_method": "both",
        "requires_identity": True,
        "estimated_days": 14,
        "priority": 70,
    },
    {
        "name": "Intelius Background",
        "slug": "intelius-background",
        "website_url": "https://backgroundcheck.intelius.com",
        "category": "background_check",
        "description": "Background check division.",
        "opt_out_email": "privacy@backgroundcheck.intelius.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 70,
    },

    # Public Records
    {
        "name": "USPhoneBook",
        "slug": "usphonebook",
        "website_url": "https://www.usphonebook.com",
        "category": "public_records",
        "description": "Public phone book directory.",
        "opt_out_url": "https://www.usphonebook.com/opt-out",
        "opt_out_email": "privacy@usphonebook.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 60,
    },
    {
        "name": "HouseHunt",
        "slug": "househunt",
        "website_url": "https://www.househunt.com",
        "category": "public_records",
        "description": "Property record aggregator.",
        "opt_out_email": "privacy@househunt.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 60,
    },
    {
        "name": "Local Records",
        "slug": "local-records",
        "website_url": "https://www.example.com",
        "category": "public_records",
        "description": "Local government records aggregator.",
        "opt_out_email": "privacy@localrecords.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 60,
    },
    {
        "name": "State Records",
        "slug": "state-records",
        "website_url": "https://www.example.com",
        "category": "public_records",
        "description": "State-level public records.",
        "opt_out_email": "privacy@staterecords.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 60,
    },
    {
        "name": "Criminal Record Search Sites",
        "slug": "criminal-records",
        "website_url": "https://www.example.com",
        "category": "public_records",
        "description": "Criminal record search services.",
        "opt_out_email": "privacy@criminalrecords.com",
        "removal_method": "email",
        "estimated_days": 14,
        "priority": 60,
    },

    # Marketing / Advertising
    {
        "name": "Sephora",
        "slug": "sephora",
        "website_url": "https://www.sephora.com",
        "category": "marketing",
        "description": "Retail beauty company that sells customer data.",
        "opt_out_email": "privacy@sephora.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 50,
    },
    {
        "name": "Target",
        "slug": "target",
        "website_url": "https://www.target.com",
        "category": "marketing",
        "description": "National retailer with loyalty data.",
        "opt_out_url": "https://help.target.com/help/privacy",
        "opt_out_email": "privacy@target.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 50,
    },
    {
        "name": "T-Mobile",
        "slug": "t-mobile",
        "website_url": "https://www.t-mobile.com",
        "category": "marketing",
        "description": "Telecom carrier that shares customer data.",
        "opt_out_url": "https://www.t-mobile.com/privacy",
        "opt_out_email": "privacy@t-mobile.com",
        "removal_method": "email",
        "estimated_days": 30,
        "priority": 50,
    },
]

class Command(BaseCommand):
    help = "Seed the data broker registry with known brokers."

    def add_arguments(self, parser):
        parser.add_argument(
            "--force",
            action="store_true",
            help="Update existing brokers with new data",
        )

    def handle(self, *args, **options):
        from core.models import Broker

        force = options.get("force", False)
        created = 0
        updated = 0

        for data in BROKERS:
            broker, is_created = Broker.objects.update_or_create(
                slug=data["slug"],
                defaults=data,
            )
            if is_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(f"Seeded {created} new brokers, updated {updated}.")
        )
