# Generated by Django 6.1.1 on 2026-09-07 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('website_url', models.URLField()),
                ('category', models.CharField(choices=[('people_search', 'People Search Sites'), ('data_broker', 'Data Brokers'), ('social_media', 'Social Media'), ('public_records', 'Public Records'), ('marketing', 'Marketing Lists'), ('background_check', 'Background Check'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('opt_out_url', models.URLField(blank=True, default='')),
                ('opt_out_email', models.EmailField(blank=True, default='', max_length=254)),
                ('removal_method', models.CharField(choices=[('email', 'Email Request'), ('web_form', 'Web Form'), ('both', 'Email + Web Form'), ('manual', 'Manual Only')], default='email', max_length=20)),
                ('web_form_config', models.JSONField(blank=True, default=dict, help_text='Config for automated form filling')),
                ('email_template', models.TextField(blank=True, default='', help_text='Custom email template. Use {name}, {email}, {address} as placeholders.')),
                ('requires_identity', models.BooleanField(default=False, help_text='Whether this broker requires ID verification')),
                ('estimated_days', models.IntegerField(default=14, help_text='Estimated days for removal')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher = processed first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_brokers', models.IntegerField(default=0)),
                ('completed_brokers', models.IntegerField(default=0)),
                ('found_count', models.IntegerField(default=0)),
                ('removed_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_interval_days', models.IntegerField(default=90)),
                ('next_scan_date', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.scan')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataStopRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stop_selling', models.BooleanField(default=True, help_text='Stop selling personal data')),
                ('stop_sharing', models.BooleanField(default=True, help_text='Stop sharing with third parties')),
                ('stop_marketing', models.BooleanField(default=True, help_text='Stop marketing communications')),
                ('confirmation_code', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_stops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'broker')},
            },
        ),
        migrations.CreateModel(
            name='RemovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('removed', 'Removed'), ('failed', 'Failed'), ('needs_manual', 'Needs Manual Action'), ('opt_out_complete', 'Opt-Out Complete')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('email', 'Email'), ('web_form', 'Web Form'), ('manual', 'Manual')], max_length=20)),
                ('found_url', models.URLField(blank=True, default='')),
                ('removal_url', models.URLField(blank=True, default='')),
                ('confirmation_code', models.CharField(blank=True, default='', max_length=200)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.broker')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.scan')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('scan', 'broker')},
            },
        ),
    ]
