# Generated by Django 5.2.17 on 2026-09-24 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('monitor', 'Run monitoring'), ('send_email', 'Send removal email'), ('fill_web_form', 'Fill removal web form'), ('verify', 'Verify removal'), ('escalate', 'Escalate to regulator')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('payload_encrypted', models.BinaryField(blank=True, null=True)),
                ('result_encrypted', models.BinaryField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True, default='')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreachEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=40)),
                ('breach_name', models.CharField(max_length=200)),
                ('breach_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('data_classes', models.JSONField(blank=True, default=list)),
                ('pwn_count', models.BigIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-breach_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('monitoring', 'Continuous monitoring'), ('auto_removal', 'Automatic removal requests'), ('dark_web', 'Dark-web / breach corpora'), ('web_search', 'Web search indexing'), ('llm', 'AI-assisted drafting')], max_length=30)),
                ('granted', models.BooleanField(default=False)),
                ('policy_version', models.CharField(default='1.0', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('breach', 'Data breach'), ('people_search', 'People-search listing'), ('public_record', 'Public record'), ('social', 'Social profile'), ('paste', 'Paste / leak'), ('dark_web', 'Dark web'), ('search_result', 'Search result'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('removal_queued', 'Removal queued'), ('removal_sent', 'Removal sent'), ('removed', 'Removed'), ('verified', 'Removed & verified'), ('reappeared', 'Reappeared'), ('dismissed', 'Dismissed'), ('failed', 'Failed')], default='new', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('site_domain', models.CharField(blank=True, default='', max_length=200)),
                ('matched_blind_index', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('matched_identifier_kind', models.CharField(blank=True, default='', max_length=20)),
                ('masked_evidence', models.CharField(blank=True, default='', max_length=300)),
                ('confidence', models.FloatField(default=0.5)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-severity', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Me', max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'identities',
                'ordering': ['-is_primary', 'label'],
            },
        ),
        migrations.CreateModel(
            name='IdentityIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('full_name', 'Full name'), ('address', 'Address'), ('username', 'Username'), ('date_of_birth', 'Date of birth'), ('ssn', 'National ID / SSN'), ('passport', 'Passport'), ('other', 'Other')], max_length=20)),
                ('value_encrypted', models.BinaryField(blank=True, null=True)),
                ('blind_index', models.CharField(db_index=True, max_length=64)),
                ('masked_value', models.CharField(blank=True, default='', max_length=120)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sources_checked', models.JSONField(blank=True, default=list)),
                ('findings_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('discord', 'Discord'), ('signal', 'Signal')], default='email', max_length=20)),
                ('target', models.CharField(help_text='Destination address/URL (encrypted at rest)', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('severity_threshold', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('signing_secret', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemovalCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('web_form', 'Web form'), ('manual', 'Manual'), ('regulator', 'Regulator complaint')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('submitted', 'Submitted'), ('awaiting_response', 'Awaiting response'), ('removed', 'Removed'), ('verified', 'Verified'), ('escalated', 'Escalated to regulator'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=40)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('confirmation_code', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemovalEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email_receipt', 'Email receipt'), ('screenshot', 'Screenshot'), ('response', 'Broker response'), ('confirmation', 'Confirmation'), ('other', 'Other')], default='other', max_length=20)),
                ('ciphertext', models.BinaryField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(blank=True, default='', max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default watchlist', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('cadence_hours', models.IntegerField(default=24)),
                ('include_breaches', models.BooleanField(default=True)),
                ('include_web_search', models.BooleanField(default=True)),
                ('include_pastes', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='core_activi_user_id_d7adda_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['scan', '-timestamp'], name='core_activi_scan_id_9c79d7_idx'),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='breachevent',
            unique_together={('source', 'breach_name')},
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exposure',
            name='breach_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exposures', to='core.breachevent'),
        ),
        migrations.AddField(
            model_name='exposure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_jobs', to='core.exposure'),
        ),
        migrations.AddField(
            model_name='identity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exposure',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exposures', to='core.identity'),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_jobs', to='core.identity'),
        ),
        migrations.AddField(
            model_name='identityidentifier',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='core.identity'),
        ),
        migrations.AddField(
            model_name='exposure',
            name='monitor_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exposures', to='core.monitorrun'),
        ),
        migrations.AddField(
            model_name='notification',
            name='exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.exposure'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationchannelconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='removalcampaign',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.broker'),
        ),
        migrations.AddField(
            model_name='removalcampaign',
            name='exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.exposure'),
        ),
        migrations.AddField(
            model_name='removalcampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_jobs', to='core.removalcampaign'),
        ),
        migrations.AddField(
            model_name='removalevidence',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.removalcampaign'),
        ),
        migrations.AddField(
            model_name='twofactordevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='core.identity'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitorrun',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.watchlist'),
        ),
        migrations.AddField(
            model_name='exposure',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exposures', to='core.watchlist'),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_jobs', to='core.watchlist'),
        ),
        migrations.AlterUniqueTogether(
            name='consentrecord',
            unique_together={('user', 'scope')},
        ),
        migrations.AddIndex(
            model_name='identityidentifier',
            index=models.Index(fields=['blind_index'], name='core_identi_blind_i_844d48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='identityidentifier',
            unique_together={('identity', 'kind', 'blind_index')},
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['user', 'status'], name='core_exposu_user_id_a1b8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['user', '-last_seen'], name='core_exposu_user_id_b1c903_idx'),
        ),
        migrations.AddIndex(
            model_name='agentjob',
            index=models.Index(fields=['user', 'status'], name='core_agentj_user_id_d5e2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentjob',
            index=models.Index(fields=['status', 'created_at'], name='core_agentj_status_6828dd_idx'),
        ),
    ]
