# Generated by Django 5.2.17 on 2026-09-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agentjob_auditevent_breachevent_consentrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannelconfig',
            name='target',
            field=models.CharField(help_text='Destination address/URL, encrypted at rest with FIELD_ENCRYPTION_KEY', max_length=500),
        ),
    ]
