# Generated by Django 5.2.17 on 2026-09-24 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notificationchannelconfig_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='removalevidence',
            options={'ordering': ['sequence', 'created_at']},
        ),
        migrations.AddField(
            model_name='broker',
            name='compliance_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='removal_rate',
            field=models.FloatField(blank=True, help_text='0-1 fraction removed', null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exposure',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='identityidentifier',
            name='linked_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_identifiers', to='core.broker'),
        ),
        migrations.AddField(
            model_name='identityidentifier',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal'), ('canary', 'Canary / tripwire'), ('alias', 'Per-broker alias')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='identityidentifier',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='removalevidence',
            name='entry_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='removalevidence',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='removalevidence',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agentjob',
            name='job_type',
            field=models.CharField(choices=[('monitor', 'Run monitoring'), ('send_email', 'Send removal email'), ('fill_web_form', 'Fill removal web form'), ('verify', 'Verify removal'), ('escalate', 'Escalate to regulator'), ('deindex', 'Request search-engine de-index')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='kind',
            field=models.CharField(choices=[('breach', 'Data breach'), ('people_search', 'People-search listing'), ('public_record', 'Public record'), ('social', 'Social profile'), ('paste', 'Paste / leak'), ('dark_web', 'Dark web'), ('search_result', 'Search result'), ('canary', 'Canary triggered (proven leak)'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='removalcampaign',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('web_form', 'Web form'), ('manual', 'Manual'), ('regulator', 'Regulator complaint'), ('deindex', 'Search-engine de-index')], default='email', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='removalevidence',
            unique_together={('campaign', 'sequence')},
        ),
    ]
